SELECT 
    '/home/grep/src/' || UGF.BOARD_ID || '/' || UGF.FILE_ID || UGF.FILE_NAME || UGF.FILE_EXT AS FILE_PATH
FROM 
    USED_GOODS_FILE UGF
JOIN 
    (SELECT BOARD_ID
     FROM USED_GOODS_BOARD
     WHERE VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
    ) UGB_MAX_VIEWS
ON 
    UGF.BOARD_ID = UGB_MAX_VIEWS.BOARD_ID
ORDER BY 
    UGF.FILE_ID DESC;